### ISSUE TITLE
requirements.txt dependencies needs to be updated

### ISSUE THREAD

**Issue by moalhaddar** [colinhartigan/valorant-skin-cli#3]
Hello, first of all I'd like to thank you for your efforts for doing this project.

I've noticed that when i've tried to install the dependencies in requirements.txt by doing
`pip install -r requirements.txt`
Then i will get some errors that some of those requirements cannot be installed, specifically:
`json`
`os`
`random`

I do believe that such libraries are already included in python, removing those from the `requirements.txt` file makes it pass the installation. 

On runtime, there is another issue that it cannot find `InquirerPy` library in `requirements.txt`, adding that one made the software work, Working requirements.txt is:
```
valclient
requests
termcolor
InquirerPy
```

Using Python 3.7.2, pip 19.0.2

**Comment by adityas-31** [comment]
Running main.py has the program working fine, but when I select randomize I am told that 
```Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "F:\valorant-skin-cli-master\valorant-skin-cli-master\src\cli\command_prompt.py", line 52, in main_loop
    self.skin_manager.randomize_skins()
  File "F:\valorant-skin-cli-master\valorant-skin-cli-master\src\flair_management\skin_manager\skin_manager.py", line 90, in randomize_skins
    Randomize(self)
  File "F:\valorant-skin-cli-master\valorant-skin-cli-master\src\flair_management\skin_manager\randomizer.py", line 15, in __init__
    for weapon in loadout['Guns']:
TypeError: 'NoneType' object is not iterable```

I have installed all packages in requirements.txt, and am running main.py. When I run main.py in the command prompt I am not getting the confirmation message that skins have been loaded, and when I check my skins I see that none of them have been detected. 
The json file in which skin data is stored is not getting updated and I believe this is the reason why skins are not getting detected. 

Python 3.9.5 and pip 21.1.3

**Comment by colinhartigan** [comment]
thanks for catching this, feel free to make a pull request or i'll update it soon
