### ISSUE TITLE
Not sure what the issue is but i have the traceback on most recent version

### ISSUE THREAD

**Issue by BigBake** [colinhartigan/valorant-skin-cli#39]
the program encountered an error; please create an issue with the traceback below if this problem persists
Traceback (most recent call last):
  File "main.py", line 28, in <module>
  File "src\startup.py", line 38, in run
  File "valclient\client.py", line 56, in __init__
ValueError: Invalid region, valid regions are: ['na', 'eu', 'latam', 'br', 'ap', 'kr', 'pbe']

**Comment by colinhartigan** [comment]
delete the folder `%APPDATA%/valorant-skin-cli` and run it again
