### ISSUE TITLE
Skins are not getting detected and 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by adityas-31** [colinhartigan/valorant-skin-cli#4]
Running main.py has the program working fine, but when I select randomize I am told that 
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "F:\valorant-skin-cli-master\valorant-skin-cli-master\src\cli\command_prompt.py", line 52, in main_loop
    self.skin_manager.randomize_skins()
  File "F:\valorant-skin-cli-master\valorant-skin-cli-master\src\flair_management\skin_manager\skin_manager.py", line 90, in randomize_skins
    Randomize(self)
  File "F:\valorant-skin-cli-master\valorant-skin-cli-master\src\flair_management\skin_manager\randomizer.py", line 15, in __init__
    for weapon in loadout['Guns']:
TypeError: 'NoneType' object is not iterable
```

I have installed all packages in requirements.txt, and am running main.py. When I run main.py in the command prompt I am not getting the confirmation message that skins have been loaded, and when I check my skins I see that none of them have been detected. 
The json file in which skin data is stored is not getting updated and I believe this is the reason why skins are not getting detected. 

Python 3.9.5 and pip 21.1.3

**Comment by TheEaterr** [comment]
I am having the same problem, no skin detected.

**Comment by colinhartigan** [comment]
what region are you in

**Comment by adityas-31** [comment]
Asia Pacific, specifically in SEA (Mumbai servers mainly)

**Comment by TheEaterr** [comment]
I am in EU

**Comment by colinhartigan** [comment]
try using the latest commit, now has support for setting region

**Comment by colinhartigan** [comment]
try [v1.0](https://github.com/colinhartigan/valorant-skin-cli/releases/tag/v1.0)
