### ISSUE TITLE
Error when randomizing on Patch 5.05 

### ISSUE THREAD

**Issue by RaySoyama** [colinhartigan/valorant-skin-cli#75]
I am getting a error when ever the skin-cli tries to auto randomizes

> Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "src\asynchronous\async_manager.py", line 18, in init_loop
  File "asyncio\base_events.py", line 579, in run_until_complete
  File "src\asynchronous\async_manager.py", line 27, in main_loop
  File "src\core_game\coregame_manager.py", line 19, in main_loop
  File "src\core_game\session.py", line 40, in update_presence
  File "src\core_game\session.py", line 25, in randomizer_check
KeyError: 'sessionLoopState'

![image](https://user-images.githubusercontent.com/42445829/189027026-8e941778-9eb4-41da-93b4-fd3c74ddad2a.png)

**Comment by colinhartigan** [comment]
please use [VIM](https://github.com/colinhartigan/valorant-inventory-manager) (skincli is no longer actively maintained)
